---

- hosts: dev
  vars_files:
    - variables/vars.yml
  tasks:


  - name: Creating prometheus user group
    group: 
      name: "{{ group_prometheus }}"
    tags:
    - tag4

  - name: Creating prometheus user
    user:
      name: "{{ user_prometheus }}"
      group: "{{ group_prometheus }}"
      system: yes
      shell: "/sbin/nologin"
      comment: "{{ user_prometheus }} nologin User"
      createhome: "no"
      state: present
    tags:
    - tag5
  
  
  - name: Install "Prometheus"
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v{{version_prometheus}}/prometheus-{{version_prometheus}}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes  
    tags:
    - tag6

  - name: Copy prometheus file to /usr/local/bin
    copy:
      src: "/tmp/prometheus-{{version_prometheus}}.linux-amd64/"
      dest: "/usr/local/bin/prometheus/"
      owner: "{{ user_prometheus }}"
      group: "{{ group_prometheus }}"
      remote_src: yes
      mode: 0755
    tags:
    - tag7


  - name: Delete "Prometheus" tmp folder
    file:
      path: '/tmp/prometheus-{{version_prometheus}}.linux-amd64'
      state: absent
    tags:
    - tag8


  - name: built "prometheus service"
    template:
      src: services/prometheus.service
      dest: /etc/systemd/system/prometheus.service
    tags:
    - tag9
 
  - name: Start prometheus service
    service:
      name: prometheus
      state: started
      enabled: yes
    tags:
    - tag10


  - name: Add node_exporter to the Prometheus Server
    ansible.builtin.blockinfile:
      path: /usr/local/bin/prometheus/prometheus.yml
      insertafter: '^scrape_config'
      block: |
        #####
          - job_name: 'node_exporter' 
            static_configs:      
              - targets:
                  {%for host in node_exporter_hosts%}
                  - '{{ host }}:9100' 
                  {%endfor%}
    notify:  restart_prometheus
    tags:
    - tag11

  - name: Adding port to firewall
    ansible.posix.firewalld:
      port: 9090/tcp
      permanent: true
      immediate: true
      state: enabled
    tags:
        - tag12


  handlers:

      - name: restart_prometheus
        service:
            name: prometheus
            state: restarted
            enabled: yes
        tags:
          - tag13

